import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
from scipy.stats import linregress

QQQ = yf.download('QQQ',start='2021-01-01',end='2021-12-31',interval='1d')

ATVI = yf.download('ATVI',start='2021-01-01',end='2021-12-31',interval='1d')
ADBE = yf.download('ADBE',start='2021-01-01',end='2021-12-31',interval='1d')
ADP = yf.download('ADP',start='2021-01-01',end='2021-12-31',interval='1d')
ABNB = yf.download('ABNB',start='2021-01-01',end='2021-12-31',interval='1d')
ALGN = yf.download('ALGN',start='2021-01-01',end='2021-12-31',interval='1d')
GOOGL = yf.download('GOOGL',start='2021-01-01',end='2021-12-31',interval='1d')
GOOG = yf.download('GOOG',start='2021-01-01',end='2021-12-31',interval='1d')
AMZN = yf.download('AMZN',start='2021-01-01',end='2021-12-31',interval='1d')
AMD = yf.download('AMD',start='2021-01-01',end='2021-12-31',interval='1d')
AEP = yf.download('AEP',start='2021-01-01',end='2021-12-31',interval='1d')
AMGN = yf.download('AMGN',start='2021-01-01',end='2021-12-31',interval='1d')
ADI = yf.download('ADI',start='2021-01-01',end='2021-12-31',interval='1d')
ANSS = yf.download('ANSS',start='2021-01-01',end='2021-12-31',interval='1d')
AAPL = yf.download('AAPL',start='2021-01-01',end='2021-12-31',interval='1d')
AMAT = yf.download('AMAT',start='2021-01-01',end='2021-12-31',interval='1d')
ASML = yf.download('ASML',start='2021-01-01',end='2021-12-31',interval='1d')
AZN = yf.download('AZN',start='2021-01-01',end='2021-12-31',interval='1d')
TEAM = yf.download('TEAM',start='2021-01-01',end='2021-12-31',interval='1d')
ADSK = yf.download('ADSK',start='2021-01-01',end='2021-12-31',interval='1d')
BIDU = yf.download('BIDU',start='2021-01-01',end='2021-12-31',interval='1d')
#BIID = yf.download('BIID',start='2021-01-01',end='2021-12-31',interval='1d')
BKNG = yf.download('BKNG',start='2021-01-01',end='2021-12-31',interval='1d')
AVGO = yf.download('AVGO',start='2021-01-01',end='2021-12-31',interval='1d')
CDNS = yf.download('CDNS',start='2021-01-01',end='2021-12-31',interval='1d')
CHTR = yf.download('CHTR',start='2021-01-01',end='2021-12-31',interval='1d')
CTAS = yf.download('CTAS',start='2021-01-01',end='2021-12-31',interval='1d')
CSCO = yf.download('CSCO',start='2021-01-01',end='2021-12-31',interval='1d')
CTSH = yf.download('CTSH',start='2021-01-01',end='2021-12-31',interval='1d')
CMCSA = yf.download('CMCSA',start='2021-01-01',end='2021-12-31',interval='1d')
#CEG = yf.download('CEG',start='2021-01-01',end='2021-12-31',interval='1d')
CPRT = yf.download('CPRT',start='2021-01-01',end='2021-12-31',interval='1d')
COST = yf.download('COST',start='2021-01-01',end='2021-12-31',interval='1d')
CRWD = yf.download('CRWD',start='2021-01-01',end='2021-12-31',interval='1d')
CSX = yf.download('CSX',start='2021-01-01',end='2021-12-31',interval='1d')
DDOG = yf.download('DDOG',start='2021-01-01',end='2021-12-31',interval='1d')
DXCM = yf.download('DXCM',start='2021-01-01',end='2021-12-31',interval='1d')
DOCU = yf.download('DOCU',start='2021-01-01',end='2021-12-31',interval='1d')
DLTR = yf.download('DLTR',start='2021-01-01',end='2021-12-31',interval='1d')
EBAY = yf.download('EBAY',start='2021-01-01',end='2021-12-31',interval='1d')
EA = yf.download('EA',start='2021-01-01',end='2021-12-31',interval='1d')
EXC = yf.download('EXC',start='2021-01-01',end='2021-12-31',interval='1d')
FAST = yf.download('FAST',start='2021-01-01',end='2021-12-31',interval='1d')
FISV = yf.download('FISV',start='2021-01-01',end='2021-12-31',interval='1d')
FTNT = yf.download('FTNT',start='2021-01-01',end='2021-12-31',interval='1d')
GILD = yf.download('GILD',start='2021-01-01',end='2021-12-31',interval='1d')
HON = yf.download('HON',start='2021-01-01',end='2021-12-31',interval='1d')
IDXX = yf.download('IDXX',start='2021-01-01',end='2021-12-31',interval='1d')
ILMN = yf.download('ILMN',start='2021-01-01',end='2021-12-31',interval='1d')
INTC = yf.download('INTC',start='2021-01-01',end='2021-12-31',interval='1d')
INTU = yf.download('INTU',start='2021-01-01',end='2021-12-31',interval='1d')
ISRG = yf.download('ISRG',start='2021-01-01',end='2021-12-31',interval='1d')
JD = yf.download('JD',start='2021-01-01',end='2021-12-31',interval='1d')
KDP = yf.download('KDP',start='2021-01-01',end='2021-12-31',interval='1d')
KLAC = yf.download('KLAC',start='2021-01-01',end='2021-12-31',interval='1d')
KHC = yf.download('KHC',start='2021-01-01',end='2021-12-31',interval='1d')
LRCX = yf.download('LRCX',start='2021-01-01',end='2021-12-31',interval='1d')
LCID = yf.download('LCID',start='2021-01-01',end='2021-12-31',interval='1d')
LULU = yf.download('LULU',start='2021-01-01',end='2021-12-31',interval='1d')
MAR = yf.download('MAR',start='2021-01-01',end='2021-12-31',interval='1d')
MRVL = yf.download('MRVL',start='2021-01-01',end='2021-12-31',interval='1d')
MTCH = yf.download('MTCH',start='2021-01-01',end='2021-12-31',interval='1d')
MELI = yf.download('MELI',start='2021-01-01',end='2021-12-31',interval='1d')
META = yf.download('META',start='2021-01-01',end='2021-12-31',interval='1d')
MCHP = yf.download('MCHP',start='2021-01-01',end='2021-12-31',interval='1d')
MU = yf.download('MU',start='2021-01-01',end='2021-12-31',interval='1d')
MSFT = yf.download('MSFT',start='2021-01-01',end='2021-12-31',interval='1d')
MRNA = yf.download('MRNA',start='2021-01-01',end='2021-12-31',interval='1d')
MDLZ = yf.download('MDLZ',start='2021-01-01',end='2021-12-31',interval='1d')
MNST = yf.download('MNST',start='2021-01-01',end='2021-12-31',interval='1d')
NTES = yf.download('NTES',start='2021-01-01',end='2021-12-31',interval='1d')
NFLX = yf.download('NFLX',start='2021-01-01',end='2021-12-31',interval='1d')
NVDA = yf.download('NVDA',start='2021-01-01',end='2021-12-31',interval='1d')
NXPI = yf.download('NXPI',start='2021-01-01',end='2021-12-31',interval='1d')
ORLY = yf.download('ORLY',start='2021-01-01',end='2021-12-31',interval='1d')
OKTA = yf.download('OKTA',start='2021-01-01',end='2021-12-31',interval='1d')
ODFL = yf.download('ODFL',start='2021-01-01',end='2021-12-31',interval='1d')
PCAR = yf.download('PCAR',start='2021-01-01',end='2021-12-31',interval='1d')
PANW = yf.download('PANW',start='2021-01-01',end='2021-12-31',interval='1d')
PAYX = yf.download('PAYX',start='2021-01-01',end='2021-12-31',interval='1d')
PYPL = yf.download('PYPL',start='2021-01-01',end='2021-12-31',interval='1d')
PEP = yf.download('PEP',start='2021-01-01',end='2021-12-31',interval='1d')
PDD = yf.download('PDD',start='2021-01-01',end='2021-12-31',interval='1d')
QCOM = yf.download('QCOM',start='2021-01-01',end='2021-12-31',interval='1d')
REGN = yf.download('REGN',start='2021-01-01',end='2021-12-31',interval='1d')
ROST = yf.download('ROST',start='2021-01-01',end='2021-12-31',interval='1d')
SGEN = yf.download('SGEN',start='2021-01-01',end='2021-12-31',interval='1d')
SIRI = yf.download('SIRI',start='2021-01-01',end='2021-12-31',interval='1d')
SWKS = yf.download('SWKS',start='2021-01-01',end='2021-12-31',interval='1d')
SPLK = yf.download('SPLK',start='2021-01-01',end='2021-12-31',interval='1d')
SBUX = yf.download('SBUX',start='2021-01-01',end='2021-12-31',interval='1d')
SNPS = yf.download('SNPS',start='2021-01-01',end='2021-12-31',interval='1d')
TMUS = yf.download('TMUS',start='2021-01-01',end='2021-12-31',interval='1d')
TSLA = yf.download('TSLA',start='2021-01-01',end='2021-12-31',interval='1d')
TXN = yf.download('TXN',start='2021-01-01',end='2021-12-31',interval='1d')
VRSN = yf.download('VRSN',start='2021-01-01',end='2021-12-31',interval='1d')
VRSK = yf.download('VRSK',start='2021-01-01',end='2021-12-31',interval='1d')
VRTX = yf.download('VRTX',start='2021-01-01',end='2021-12-31',interval='1d')
WBA = yf.download('WBA',start='2021-01-01',end='2021-12-31',interval='1d')
WDAY = yf.download('WDAY',start='2021-01-01',end='2021-12-31',interval='1d')
XEL = yf.download('XEL',start='2021-01-01',end='2021-12-31',interval='1d')
ZM = yf.download('ZM',start='2021-01-01',end='2021-12-31',interval='1d')
ZS = yf.download('ZS',start='2021-01-01',end='2021-12-31',interval='1d')

QQQ.to_csv('qqq.csv')
ATVI.to_csv('ATVI.csv')
ADBE.to_csv('ADBE.csv')
ADP.to_csv('ADP.csv')
ABNB.to_csv('ABNB.csv')
ALGN.to_csv('ALGN.csv')
GOOGL.to_csv('GOOGL.csv')
GOOG.to_csv('GOOG.csv')
AMZN.to_csv('AMZN.csv')
AMD.to_csv('AMD.csv')
AEP.to_csv('AEP.csv')
AMGN.to_csv('AMGN.csv')
ADI.to_csv('ADI.csv')
ANSS.to_csv('ANSS.csv')
AAPL.to_csv('AAPL.csv')
AMAT.to_csv('AMAT.csv')
ASML.to_csv('ASML.csv')
AZN.to_csv('AZN.csv')
TEAM.to_csv('TEAM.csv')
ADSK.to_csv('ADSK.csv')
BIDU.to_csv('BIDU.csv')
#BIID.to_csv('BIID.csv')
BKNG.to_csv('BKNG.csv')
AVGO.to_csv('AVGO.csv')
CDNS.to_csv('CDNS.csv')
CHTR.to_csv('CHTR.csv')
CTAS.to_csv('CTAS.csv')
CSCO.to_csv('CSCO.csv')
CTSH.to_csv('CTSH.csv')
CMCSA.to_csv('CMCSA.csv')
#CEG.to_csv('CEG.csv')
CPRT.to_csv('CPRT.csv')
COST.to_csv('COST.csv')
CRWD.to_csv('CRWD.csv')
CSX.to_csv('CSX.csv')
DDOG.to_csv('DDOG.csv')
DXCM.to_csv('DXCM.csv')
DOCU.to_csv('DOCU.csv')
DLTR.to_csv('DLTR.csv')
EBAY.to_csv('EBAY.csv')
EA.to_csv('EA.csv')
EXC.to_csv('EXC.csv')
FAST.to_csv('FAST.csv')
FISV.to_csv('FISV.csv')
FTNT.to_csv('FTNT.csv')
GILD.to_csv('GILD.csv')
HON.to_csv('HON.csv')
IDXX.to_csv('IDXX.csv')
ILMN.to_csv('ILMN.csv')
INTC.to_csv('INTC.csv')
INTU.to_csv('INTU.csv')
ISRG.to_csv('ISRG.csv')
JD.to_csv('JD.csv')
KDP.to_csv('KDP.csv')
KLAC.to_csv('KLAC.csv')
KHC.to_csv('KHC.csv')
LRCX.to_csv('LRCX.csv')
LCID.to_csv('LCID.csv')
LULU.to_csv('LULU.csv')
MAR.to_csv('MAR.csv')
MRVL.to_csv('MRVL.csv')
MTCH.to_csv('MTCH.csv')
MELI.to_csv('MELI.csv')
META.to_csv('META.csv')
MCHP.to_csv('MCHP.csv')
MU.to_csv('MU.csv')
MSFT.to_csv('MSFT.csv')
MRNA.to_csv('MRNA.csv')
MDLZ.to_csv('MDLZ.csv')
MNST.to_csv('MNST.csv')
NTES.to_csv('NTES.csv')
NFLX.to_csv('NFLX.csv')
NVDA.to_csv('NVDA.csv')
NXPI.to_csv('NXPI.csv')
ORLY.to_csv('ORLY.csv')
OKTA.to_csv('OKTA.csv')
ODFL.to_csv('ODFL.csv')
PCAR.to_csv('PCAR.csv')
PANW.to_csv('PANW.csv')
PAYX.to_csv('PAYX.csv')
PYPL.to_csv('PYPL.csv')
PEP.to_csv('PEP.csv')
PDD.to_csv('PDD.csv')
QCOM.to_csv('QCOM.csv')
REGN.to_csv('REGN.csv')
ROST.to_csv('ROST.csv')
SGEN.to_csv('SGEN.csv')
SIRI.to_csv('SIRI.csv')
SWKS.to_csv('SWKS.csv')
SPLK.to_csv('SPLK.csv')
SBUX.to_csv('SBUX.csv')
SNPS.to_csv('SNPS.csv')
TMUS.to_csv('TMUS.csv')
TSLA.to_csv('TSLA.csv')
TXN.to_csv('TXN.csv')
VRSN.to_csv('VRSN.csv')
VRSK.to_csv('VRSK.csv')
VRTX.to_csv('VRTX.csv')
WBA.to_csv('WBA.csv')
WDAY.to_csv('WDAY.csv')
XEL.to_csv('XEL.csv')
ZM.to_csv('ZM.csv')
ZS.to_csv('ZS.csv')

QQQ = pd.read_csv('QQQ.csv'); QQQ['pct'] = QQQ['Close'].pct_change()
ATVI = pd.read_csv('ATVI.csv'); ATVI['pct'] = ATVI['Close'].pct_change()
ADBE = pd.read_csv('ADBE.csv'); ADBE['pct'] = ADBE['Close'].pct_change()
ADP = pd.read_csv('ADP.csv'); ADP['pct'] = ADP['Close'].pct_change()
ABNB = pd.read_csv('ABNB.csv'); ABNB['pct'] = ABNB['Close'].pct_change()
ALGN = pd.read_csv('ALGN.csv'); ALGN['pct'] = ALGN['Close'].pct_change()
GOOGL = pd.read_csv('GOOGL.csv'); GOOGL['pct'] = GOOGL['Close'].pct_change()
GOOG = pd.read_csv('GOOG.csv'); GOOG['pct'] = GOOG['Close'].pct_change()
AMZN = pd.read_csv('AMZN.csv'); AMZN['pct'] = AMZN['Close'].pct_change()
AMD = pd.read_csv('AMD.csv'); AMD['pct'] = AMD['Close'].pct_change()
AEP = pd.read_csv('AEP.csv'); AEP['pct'] = AEP['Close'].pct_change()
AMGN = pd.read_csv('AMGN.csv'); AMGN['pct'] = AMGN['Close'].pct_change()
ADI = pd.read_csv('ADI.csv'); ADI['pct'] = ADI['Close'].pct_change()
ANSS = pd.read_csv('ANSS.csv'); ANSS['pct'] = ANSS['Close'].pct_change()
AAPL = pd.read_csv('AAPL.csv'); AAPL['pct'] = AAPL['Close'].pct_change()
AMAT = pd.read_csv('AMAT.csv'); AMAT['pct'] = AMAT['Close'].pct_change()
ASML = pd.read_csv('ASML.csv'); ASML['pct'] = ASML['Close'].pct_change()
AZN = pd.read_csv('AZN.csv'); AZN['pct'] = AZN['Close'].pct_change()
TEAM = pd.read_csv('TEAM.csv'); TEAM['pct'] = TEAM['Close'].pct_change()
ADSK = pd.read_csv('ADSK.csv'); ADSK['pct'] = ADSK['Close'].pct_change()
BIDU = pd.read_csv('BIDU.csv'); BIDU['pct'] = BIDU['Close'].pct_change()
BKNG = pd.read_csv('BKNG.csv'); BKNG['pct'] = BKNG['Close'].pct_change()
AVGO = pd.read_csv('AVGO.csv'); AVGO['pct'] = AVGO['Close'].pct_change()
CDNS = pd.read_csv('CDNS.csv'); CDNS['pct'] = CDNS['Close'].pct_change()
CHTR = pd.read_csv('CHTR.csv'); CHTR['pct'] = CHTR['Close'].pct_change()
CTAS = pd.read_csv('CTAS.csv'); CTAS['pct'] = CTAS['Close'].pct_change()
CSCO = pd.read_csv('CSCO.csv'); CSCO['pct'] = CSCO['Close'].pct_change()
CTSH = pd.read_csv('CTSH.csv'); CTSH['pct'] = CTSH['Close'].pct_change()
CMCSA = pd.read_csv('CMCSA.csv'); CMCSA['pct'] = CMCSA['Close'].pct_change()
CPRT = pd.read_csv('CPRT.csv'); CPRT['pct'] = CPRT['Close'].pct_change()
COST = pd.read_csv('COST.csv'); COST['pct'] = COST['Close'].pct_change()
CRWD = pd.read_csv('CRWD.csv'); CRWD['pct'] = CRWD['Close'].pct_change()
CSX = pd.read_csv('CSX.csv'); CSX['pct'] = CSX['Close'].pct_change()
DDOG = pd.read_csv('DDOG.csv'); DDOG['pct'] = DDOG['Close'].pct_change()
DXCM = pd.read_csv('DXCM.csv'); DXCM['pct'] = DXCM['Close'].pct_change()
DOCU = pd.read_csv('DOCU.csv'); DOCU['pct'] = DOCU['Close'].pct_change()
DLTR = pd.read_csv('DLTR.csv'); DLTR['pct'] = DLTR['Close'].pct_change()
EBAY = pd.read_csv('EBAY.csv'); EBAY['pct'] = EBAY['Close'].pct_change()
EA = pd.read_csv('EA.csv'); EA['pct'] = EA['Close'].pct_change()
EXC = pd.read_csv('EXC.csv'); EXC['pct'] = EXC['Close'].pct_change()
FAST = pd.read_csv('FAST.csv'); FAST['pct'] = FAST['Close'].pct_change()
FISV = pd.read_csv('FISV.csv'); FISV['pct'] = FISV['Close'].pct_change()
FTNT = pd.read_csv('FTNT.csv'); FTNT['pct'] = FTNT['Close'].pct_change()
GILD = pd.read_csv('GILD.csv'); GILD['pct'] = GILD['Close'].pct_change()
HON = pd.read_csv('HON.csv'); HON['pct'] = HON['Close'].pct_change()
IDXX = pd.read_csv('IDXX.csv'); IDXX['pct'] = IDXX['Close'].pct_change()
ILMN = pd.read_csv('ILMN.csv'); ILMN['pct'] = ILMN['Close'].pct_change()
INTC = pd.read_csv('INTC.csv'); INTC['pct'] = INTC['Close'].pct_change()
INTU = pd.read_csv('INTU.csv'); INTU['pct'] = INTU['Close'].pct_change()
ISRG = pd.read_csv('ISRG.csv'); ISRG['pct'] = ISRG['Close'].pct_change()
JD = pd.read_csv('JD.csv'); JD['pct'] = JD['Close'].pct_change()
KDP = pd.read_csv('KDP.csv'); KDP['pct'] = KDP['Close'].pct_change()
KLAC = pd.read_csv('KLAC.csv'); KLAC['pct'] = KLAC['Close'].pct_change()
KHC = pd.read_csv('KHC.csv'); KHC['pct'] = KHC['Close'].pct_change()
LRCX = pd.read_csv('LRCX.csv'); LRCX['pct'] = LRCX['Close'].pct_change()
LCID = pd.read_csv('LCID.csv'); LCID['pct'] = LCID['Close'].pct_change()
LULU = pd.read_csv('LULU.csv'); LULU['pct'] = LULU['Close'].pct_change()
MAR = pd.read_csv('MAR.csv'); MAR['pct'] = MAR['Close'].pct_change()
MRVL = pd.read_csv('MRVL.csv'); MRVL['pct'] = MRVL['Close'].pct_change()
MTCH = pd.read_csv('MTCH.csv'); MTCH['pct'] = MTCH['Close'].pct_change()
MELI = pd.read_csv('MELI.csv'); MELI['pct'] = MELI['Close'].pct_change()
META = pd.read_csv('META.csv'); META['pct'] = META['Close'].pct_change()
MCHP = pd.read_csv('MCHP.csv'); MCHP['pct'] = MCHP['Close'].pct_change()
MU = pd.read_csv('MU.csv'); MU['pct'] = MU['Close'].pct_change()
MSFT = pd.read_csv('MSFT.csv'); MSFT['pct'] = MSFT['Close'].pct_change()
MRNA = pd.read_csv('MRNA.csv'); MRNA['pct'] = MRNA['Close'].pct_change()
MDLZ = pd.read_csv('MDLZ.csv'); MDLZ['pct'] = MDLZ['Close'].pct_change()
MNST = pd.read_csv('MNST.csv'); MNST['pct'] = MNST['Close'].pct_change()
NTES = pd.read_csv('NTES.csv'); NTES['pct'] = NTES['Close'].pct_change()
NFLX = pd.read_csv('NFLX.csv'); NFLX['pct'] = NFLX['Close'].pct_change()
NVDA = pd.read_csv('NVDA.csv'); NVDA['pct'] = NVDA['Close'].pct_change()
NXPI = pd.read_csv('NXPI.csv'); NXPI['pct'] = NXPI['Close'].pct_change()
ORLY = pd.read_csv('ORLY.csv'); ORLY['pct'] = ORLY['Close'].pct_change()
OKTA = pd.read_csv('OKTA.csv'); OKTA['pct'] = OKTA['Close'].pct_change()
ODFL = pd.read_csv('ODFL.csv'); ODFL['pct'] = ODFL['Close'].pct_change()
PCAR = pd.read_csv('PCAR.csv'); PCAR['pct'] = PCAR['Close'].pct_change()
PANW = pd.read_csv('PANW.csv'); PANW['pct'] = PANW['Close'].pct_change()
PAYX = pd.read_csv('PAYX.csv'); PAYX['pct'] = PAYX['Close'].pct_change()
PYPL = pd.read_csv('PYPL.csv'); PYPL['pct'] = PYPL['Close'].pct_change()
PEP = pd.read_csv('PEP.csv'); PEP['pct'] = PEP['Close'].pct_change()
PDD = pd.read_csv('PDD.csv'); PDD['pct'] = PDD['Close'].pct_change()
QCOM = pd.read_csv('QCOM.csv'); QCOM['pct'] = QCOM['Close'].pct_change()
REGN = pd.read_csv('REGN.csv'); REGN['pct'] = REGN['Close'].pct_change()
ROST = pd.read_csv('ROST.csv'); ROST['pct'] = ROST['Close'].pct_change()
SGEN = pd.read_csv('SGEN.csv'); SGEN['pct'] = SGEN['Close'].pct_change()
SIRI = pd.read_csv('SIRI.csv'); SIRI['pct'] = SIRI['Close'].pct_change()
SWKS = pd.read_csv('SWKS.csv'); SWKS['pct'] = SWKS['Close'].pct_change()
SPLK = pd.read_csv('SPLK.csv'); SPLK['pct'] = SPLK['Close'].pct_change()
SBUX = pd.read_csv('SBUX.csv'); SBUX['pct'] = SBUX['Close'].pct_change()
SNPS = pd.read_csv('SNPS.csv'); SNPS['pct'] = SNPS['Close'].pct_change()
TMUS = pd.read_csv('TMUS.csv'); TMUS['pct'] = TMUS['Close'].pct_change()
TSLA = pd.read_csv('TSLA.csv'); TSLA['pct'] = TSLA['Close'].pct_change()
TXN = pd.read_csv('TXN.csv'); TXN['pct'] = TXN['Close'].pct_change()
VRSN = pd.read_csv('VRSN.csv'); VRSN['pct'] = VRSN['Close'].pct_change()
VRSK = pd.read_csv('VRSK.csv'); VRSK['pct'] = VRSK['Close'].pct_change()
VRTX = pd.read_csv('VRTX.csv'); VRTX['pct'] = VRTX['Close'].pct_change()
WBA = pd.read_csv('WBA.csv'); WBA['pct'] = WBA['Close'].pct_change()
WDAY = pd.read_csv('WDAY.csv'); WDAY['pct'] = WDAY['Close'].pct_change()
XEL = pd.read_csv('XEL.csv'); XEL['pct'] = XEL['Close'].pct_change()
ZM = pd.read_csv('ZM.csv'); ZM['pct'] = ZM['Close'].pct_change()
ZS = pd.read_csv('ZS.csv'); ZS['pct'] = ZS['Close'].pct_change()
